require: rubocop-performance

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.6
  # uncomment if use rails cops
  # TargetRailsVersion: 5.0

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/IndentationConsistency:
    EnforcedStyle: indented_internal_methods

Metrics/ParameterLists:
  Max: 7

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
