require: rubocop-performance

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    - "config/rspec.yml"
    - "config/performance.yml"

AllCops:
  TargetRubyVersion: 3.1
  # uncomment if use rails cops
  # TargetRailsVersion: 5.0
  NewCops: enable
  SuggestExtensions: false

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/IndentationConsistency:
    EnforcedStyle: indented_internal_methods

Metrics/ParameterLists:
  Max: 7

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
