inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.4
  # uncomment if use rails cops
  # TargetRailsVersion: 5.0
